### ISSUE TITLE
Не загружается прошивка.

### ISSUE THREAD

**Issue by MikePavol** [ra0sms/Azimuth_control_console#1]
Приветствую, Антон.
Не получается загрузить прошивку. Windows 10, COM порт определился в STM32 Flash Loader, файл Rotator.bin, Page size 128, скорость 115200. После нажатия на кнопку «Write Firmware and Start» лишь звучит сигнал и ничего не происходит. Пробовал разные компы с W10, но ничего не помогает . Никаких ошибок тоже нет. Что делать? Спасибо заранее .

**Comment by ra0sms** [comment]
Вы поставили перемычку BOOT на плате в положение ON?

**Comment by MikePavol** [comment]
Да,конечно.

**Comment by MikePavol** [comment]
UPD:
Установил STM32CubeProgrammer, всё прошилось без проблем.

**Comment by ra0sms** [comment]
Микросхема CH340 с буквой C? Попробуйте  загрузить с помощью STM32Cube Programmer.

**Comment by ra0sms** [comment]
> UPD: Установил STM32CubeProgrammer, всё прошилось без проблем.

**Comment by MikePavol** [comment]
Теперь мне надо поменять число импульсов в программе, Установил STM32CubeIDE, разбираюсь, как правильно загрузить проект и все настройки и библиотеки...
